//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace istEncuestasMVC.ServiceITLProxy {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceITLSoap", Namespace="http://tempuri.org/")]
    public partial class ServiceITL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EncuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SubFamiliaOperationCompleted;
        
        private System.Threading.SendOrPostCallback DetalleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngresarRespEncuestaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrabajadorNominadoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceITL() {
            this.Url = global::istEncuestasMVC.Properties.Settings.Default.istEncuestasMVC_ServiceITLProxy_ServiceITL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EncuestaCompletedEventHandler EncuestaCompleted;
        
        /// <remarks/>
        public event SubFamiliaCompletedEventHandler SubFamiliaCompleted;
        
        /// <remarks/>
        public event DetalleCompletedEventHandler DetalleCompleted;
        
        /// <remarks/>
        public event IngresarRespEncuestaCompletedEventHandler IngresarRespEncuestaCompleted;
        
        /// <remarks/>
        public event TrabajadorNominadoCompletedEventHandler TrabajadorNominadoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Encuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Encuesta(string id_Encuesta) {
            object[] results = this.Invoke("Encuesta", new object[] {
                        id_Encuesta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EncuestaAsync(string id_Encuesta) {
            this.EncuestaAsync(id_Encuesta, null);
        }
        
        /// <remarks/>
        public void EncuestaAsync(string id_Encuesta, object userState) {
            if ((this.EncuestaOperationCompleted == null)) {
                this.EncuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEncuestaOperationCompleted);
            }
            this.InvokeAsync("Encuesta", new object[] {
                        id_Encuesta}, this.EncuestaOperationCompleted, userState);
        }
        
        private void OnEncuestaOperationCompleted(object arg) {
            if ((this.EncuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EncuestaCompleted(this, new EncuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SubFamilia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SubFamilia(string id_Encuesta) {
            object[] results = this.Invoke("SubFamilia", new object[] {
                        id_Encuesta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SubFamiliaAsync(string id_Encuesta) {
            this.SubFamiliaAsync(id_Encuesta, null);
        }
        
        /// <remarks/>
        public void SubFamiliaAsync(string id_Encuesta, object userState) {
            if ((this.SubFamiliaOperationCompleted == null)) {
                this.SubFamiliaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSubFamiliaOperationCompleted);
            }
            this.InvokeAsync("SubFamilia", new object[] {
                        id_Encuesta}, this.SubFamiliaOperationCompleted, userState);
        }
        
        private void OnSubFamiliaOperationCompleted(object arg) {
            if ((this.SubFamiliaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SubFamiliaCompleted(this, new SubFamiliaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Detalle", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Detalle(string id_Encuesta, string id_SubFamilia) {
            object[] results = this.Invoke("Detalle", new object[] {
                        id_Encuesta,
                        id_SubFamilia});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DetalleAsync(string id_Encuesta, string id_SubFamilia) {
            this.DetalleAsync(id_Encuesta, id_SubFamilia, null);
        }
        
        /// <remarks/>
        public void DetalleAsync(string id_Encuesta, string id_SubFamilia, object userState) {
            if ((this.DetalleOperationCompleted == null)) {
                this.DetalleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDetalleOperationCompleted);
            }
            this.InvokeAsync("Detalle", new object[] {
                        id_Encuesta,
                        id_SubFamilia}, this.DetalleOperationCompleted, userState);
        }
        
        private void OnDetalleOperationCompleted(object arg) {
            if ((this.DetalleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DetalleCompleted(this, new DetalleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IngresarRespEncuesta", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IngresarRespEncuesta(int folEnc, string codClase, string glsRsp, string glsObservacion, string rutEmp, string rutEje, string rutEjeEmp, string glsNomEjeEmp, string glsCargoEjeEmp, string glsCorreoEjeEmp, string glsFonoEjeEmp, string idUsu, string idFun) {
            object[] results = this.Invoke("IngresarRespEncuesta", new object[] {
                        folEnc,
                        codClase,
                        glsRsp,
                        glsObservacion,
                        rutEmp,
                        rutEje,
                        rutEjeEmp,
                        glsNomEjeEmp,
                        glsCargoEjeEmp,
                        glsCorreoEjeEmp,
                        glsFonoEjeEmp,
                        idUsu,
                        idFun});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IngresarRespEncuestaAsync(int folEnc, string codClase, string glsRsp, string glsObservacion, string rutEmp, string rutEje, string rutEjeEmp, string glsNomEjeEmp, string glsCargoEjeEmp, string glsCorreoEjeEmp, string glsFonoEjeEmp, string idUsu, string idFun) {
            this.IngresarRespEncuestaAsync(folEnc, codClase, glsRsp, glsObservacion, rutEmp, rutEje, rutEjeEmp, glsNomEjeEmp, glsCargoEjeEmp, glsCorreoEjeEmp, glsFonoEjeEmp, idUsu, idFun, null);
        }
        
        /// <remarks/>
        public void IngresarRespEncuestaAsync(int folEnc, string codClase, string glsRsp, string glsObservacion, string rutEmp, string rutEje, string rutEjeEmp, string glsNomEjeEmp, string glsCargoEjeEmp, string glsCorreoEjeEmp, string glsFonoEjeEmp, string idUsu, string idFun, object userState) {
            if ((this.IngresarRespEncuestaOperationCompleted == null)) {
                this.IngresarRespEncuestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngresarRespEncuestaOperationCompleted);
            }
            this.InvokeAsync("IngresarRespEncuesta", new object[] {
                        folEnc,
                        codClase,
                        glsRsp,
                        glsObservacion,
                        rutEmp,
                        rutEje,
                        rutEjeEmp,
                        glsNomEjeEmp,
                        glsCargoEjeEmp,
                        glsCorreoEjeEmp,
                        glsFonoEjeEmp,
                        idUsu,
                        idFun}, this.IngresarRespEncuestaOperationCompleted, userState);
        }
        
        private void OnIngresarRespEncuestaOperationCompleted(object arg) {
            if ((this.IngresarRespEncuestaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngresarRespEncuestaCompleted(this, new IngresarRespEncuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TrabajadorNominado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TrabajadorNominado(string rutPer) {
            object[] results = this.Invoke("TrabajadorNominado", new object[] {
                        rutPer});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TrabajadorNominadoAsync(string rutPer) {
            this.TrabajadorNominadoAsync(rutPer, null);
        }
        
        /// <remarks/>
        public void TrabajadorNominadoAsync(string rutPer, object userState) {
            if ((this.TrabajadorNominadoOperationCompleted == null)) {
                this.TrabajadorNominadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrabajadorNominadoOperationCompleted);
            }
            this.InvokeAsync("TrabajadorNominado", new object[] {
                        rutPer}, this.TrabajadorNominadoOperationCompleted, userState);
        }
        
        private void OnTrabajadorNominadoOperationCompleted(object arg) {
            if ((this.TrabajadorNominadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrabajadorNominadoCompleted(this, new TrabajadorNominadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void EncuestaCompletedEventHandler(object sender, EncuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SubFamiliaCompletedEventHandler(object sender, SubFamiliaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubFamiliaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SubFamiliaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void DetalleCompletedEventHandler(object sender, DetalleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DetalleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DetalleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void IngresarRespEncuestaCompletedEventHandler(object sender, IngresarRespEncuestaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngresarRespEncuestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngresarRespEncuestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void TrabajadorNominadoCompletedEventHandler(object sender, TrabajadorNominadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrabajadorNominadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrabajadorNominadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591